(function(){
  'use strict';
  var bootstrap=document.getElementById('pair-home-bootstrap');
  var shell=document.getElementById('pair-home-shell');
  var frame=document.getElementById('pair-home-frame');
  var canvas=document.getElementById('pair-home-canvas');
  if(!bootstrap||!shell||!frame||!canvas)return;
  var config=JSON.parse(bootstrap.textContent||'{}');
  var state={editing:false,selectedId:null,backgroundColor:config.backgroundColor||'#F2ECE5',backgroundImage:config.backgroundImage||'',frameTheme:/^(web|diary|mac)$/.test(config.frameTheme||'')?config.frameTheme:'diary',widgets:Array.isArray(config.widgets)?config.widgets:[]};
  var interaction=null,activeUploadWidgetId=null,activeAudioWidgetId=null,statusTimer=null,isSaving=false;
  var savedState=serializeState();
  function clamp(v,min,max){return Math.max(min,Math.min(max,v));}
  function byId(id){return state.widgets.find(function(w){return w.id===id;});}
  function newId(type){return type+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);}
  function serializeState(){return JSON.stringify({backgroundColor:state.backgroundColor,backgroundImage:state.backgroundImage,frameTheme:state.frameTheme,widgets:state.widgets});}
  function clone(value){return JSON.parse(JSON.stringify(value));}
  function frameRatio(widget){var value=String((widget.data&&widget.data.ratio)||'1:1').split(':');var width=Number(value[0]),height=Number(value[1]);return width>0&&height>0?width/height:1;}
  function fixedRatio(widget){if(widget.type==='image')return frameRatio(widget);if(widget.type==='sticker'&&Number(widget.data&&widget.data.aspect)>0)return Number(widget.data.aspect);return 0;}
  function visualHeightPercent(widget,rect){var ratio=fixedRatio(widget);if(!ratio)return Number(widget.h);return ((Number(widget.w)/100*rect.width)/ratio)/rect.height*100;}
  // Constrain the rotated visible bounds, not just the unrotated percentages.
  // Rendering uses a copy so resizing the viewport never changes saved layout data.
  function widgetGeometry(widget,rect){
    var width=clamp(Number(widget.w)||4,4,96)/100*rect.width;
    var ratio=fixedRatio(widget);
    var height=ratio?width/ratio:clamp(Number(widget.h)||4,4,96)/100*rect.height;
    var angle=(Number(widget.rotation)||0)*Math.PI/180;
    var cos=Math.abs(Math.cos(angle)),sin=Math.abs(Math.sin(angle));
    var boundsWidth=width*cos+height*sin,boundsHeight=width*sin+height*cos;
    var scale=Math.min(1,rect.width/boundsWidth,rect.height/boundsHeight,.96*rect.width/width,.96*rect.height/height);
    width*=scale;height*=scale;boundsWidth*=scale;boundsHeight*=scale;
    var insetX=Math.max(width,boundsWidth)/2,insetY=Math.max(height,boundsHeight)/2;
    var centerX=clamp((Number(widget.x)||0)/100*rect.width+width/2,insetX,rect.width-insetX);
    var centerY=clamp((Number(widget.y)||0)/100*rect.height+height/2,insetY,rect.height-insetY);
    return {x:(centerX-width/2)/rect.width*100,y:(centerY-height/2)/rect.height*100,w:width/rect.width*100,h:height/rect.height*100};
  }
  function fitFixedRatioWidget(widget){
    if(!widget)return;var rect=canvas.getBoundingClientRect();if(!rect.width||!rect.height)return;
    var geometry=widgetGeometry(widget,rect);
    widget.x=geometry.x;widget.y=geometry.y;widget.w=geometry.w;widget.h=geometry.h;
  }
  function isDirty(){return serializeState()!==savedState;}
  function updateDirtyUi(){if(!config.admin)return;var dirty=isDirty();var toggle=document.getElementById('pair-editor-toggle');var reset=document.getElementById('pair-reset');var saveButton=document.getElementById('pair-save');if(toggle){toggle.classList.toggle('is-dirty',dirty);toggle.textContent=state.editing?'꾸미기 종료'+(dirty?' · 미저장':''):'꾸미기'+(dirty?' · 미저장':'');}if(reset)reset.disabled=!dirty||isSaving;if(saveButton)saveButton.disabled=!dirty||isSaving;}
  function markDirty(){updateDirtyUi();}
  function restoreSaved(){var saved=JSON.parse(savedState);state.backgroundColor=saved.backgroundColor;state.backgroundImage=saved.backgroundImage;state.frameTheme=saved.frameTheme||'diary';state.widgets=clone(saved.widgets);state.selectedId=null;render();updateDirtyUi();showStatus('저장된 상태로 되돌렸습니다.');}
  function safeLink(url){url=String(url||'').trim();return /^(?:javascript|data|vbscript):/i.test(url)?'':url;}
  function navigate(url,newTab){url=safeLink(url);if(!url||state.editing)return;if(newTab||/^https?:\/\//i.test(url)){window.open(url,'_blank','noopener');return;}if(window.parent&&window.parent!==window)window.parent.postMessage({type:'navigate',url:url},'*');else window.location.href=url;}
  function applyBackground(){shell.style.setProperty('--pair-bg',state.backgroundColor);shell.style.backgroundImage=state.backgroundImage?'url("'+state.backgroundImage.replace(/"/g,'%22')+'")':'none';}
  function applyFrameTheme(){frame.classList.remove('theme-web','theme-diary','theme-mac');frame.classList.add('theme-'+state.frameTheme);}
  function ddayText(widget){var target=new Date(widget.data.date+'T00:00:00'),today=new Date();today.setHours(0,0,0,0);var elapsed=Math.round((today-target)/86400000);if(widget.data.mode==='until'){if(elapsed===0)return'D-DAY';return elapsed<0?'D-'+Math.abs(elapsed):'D+'+elapsed;}if(elapsed===0&&!widget.data.include_today)return'D-DAY';if(elapsed>=0&&widget.data.include_today)elapsed+=1;return elapsed>=0?'D+'+elapsed:'D-'+Math.abs(elapsed);}
  function renderContent(widget,content){
    var data=widget.data||{};
    if(widget.type==='image'){
      content.className='pair-widget-content pair-widget-image shape-'+(data.shape||'rounded');
      content.style.borderRadius=data.shape==='circle'?'50%':(data.shape==='square'?'0':clamp(data.radius==null?18:Number(data.radius),0,120)+'px');
      if(data.src){var img=document.createElement('img');var focusX=data.focus_x==null?50:Number(data.focus_x),focusY=data.focus_y==null?50:Number(data.focus_y);img.src=data.src;img.alt=data.alt||'';img.style.objectPosition=focusX+'% '+focusY+'%';img.style.transform='scale('+clamp(Number(data.zoom)||1,1,3)+')';img.style.transformOrigin=focusX+'% '+focusY+'%';content.appendChild(img);}else addEmpty(content,'이미지 프레임');
      content.addEventListener('click',function(){navigate(data.link);});
    }else if(widget.type==='sticker'){
      content.className='pair-widget-content pair-widget-sticker';
      content.style.opacity=clamp(data.opacity==null?1:Number(data.opacity),.1,1);
      if(data.src){var sticker=document.createElement('img');sticker.src=data.src;sticker.alt=data.alt||'';sticker.style.transform=data.flip_x?'scaleX(-1)':'none';content.appendChild(sticker);}else addEmpty(content,'STICKER');
      content.addEventListener('click',function(){navigate(data.link);});
    }else if(widget.type==='text'){
      content.className='pair-widget-content pair-widget-text';var fontMap={sans:'Pretendard,"Noto Sans KR","Malgun Gothic",sans-serif',serif:'Georgia,"Noto Serif KR",Batang,serif',handwriting:'"Segoe Print","Nanum Pen Script","Malgun Gothic",cursive'};content.style.fontFamily=fontMap[data.font]||fontMap.serif;content.style.fontSize='max(10px, calc('+clamp(data.font_size==null?48:Number(data.font_size),12,160)+'px * var(--pair-text-scale, 1)))';content.style.color=data.color||'#282326';content.style.fontWeight=data.weight==='bold'?'700':'400';content.style.textAlign=data.align||'left';content.style.justifyContent=data.align==='center'?'center':(data.align==='right'?'flex-end':'flex-start');content.style.lineHeight=clamp(data.line_height==null?1.05:Number(data.line_height),.8,2.5);content.textContent=data.text||'텍스트';content.addEventListener('click',function(){navigate(data.link);});
    }else if(widget.type==='dday'){
      content.className='pair-widget-content pair-widget-dday style-'+(data.style||'lcd');content.style.setProperty('--widget-accent',data.accent||'#829782');var label=document.createElement('small');label.textContent=data.title||'D-DAY';var value=document.createElement('strong');value.textContent=ddayText(widget);content.append(label,value);if(data.show_date!==false){var date=document.createElement('time');date.dateTime=data.date||'';date.textContent=String(data.date||'').replace(/-/g,'.');content.appendChild(date);}
    }else if(widget.type==='bgm'){
      content.className='pair-widget-content pair-widget-bgm';var title=document.createElement('strong');title.textContent=data.title||'BGM';var audio=document.createElement('audio');audio.preload='metadata';audio.loop=!!data.loop;audio.volume=clamp(data.volume==null?.8:Number(data.volume),0,1);if(data.src)audio.src=data.src;
      var controls=document.createElement('div');controls.className='pair-bgm-controls';
      var play=document.createElement('button');play.type='button';play.className='pair-bgm-play';play.setAttribute('aria-label','음악 재생');play.disabled=!data.src;
      var progress=document.createElement('input');progress.type='range';progress.min=0;progress.max=100;progress.step=.1;progress.value=0;progress.disabled=true;progress.setAttribute('aria-label','재생 위치');
      var meta=document.createElement('div');meta.className='pair-bgm-meta';
      var elapsed=document.createElement('span');elapsed.textContent=data.src?'0:00':'음원을 추가해 주세요';
      var volume=document.createElement('input');volume.type='range';volume.min=0;volume.max=1;volume.step=.05;volume.value=audio.volume;volume.setAttribute('aria-label','음량');
      function updatePlayback(){play.classList.toggle('is-playing',!audio.paused);play.setAttribute('aria-label',audio.paused?'음악 재생':'음악 일시정지');}
      play.addEventListener('click',function(){if(state.editing)return;if(audio.paused){audio.play().catch(function(){elapsed.textContent='재생할 수 없는 음원';});}else audio.pause();});
      audio.addEventListener('play',updatePlayback);audio.addEventListener('pause',updatePlayback);audio.addEventListener('ended',updatePlayback);
      audio.addEventListener('loadedmetadata',function(){progress.disabled=!Number.isFinite(audio.duration)||audio.duration<=0;});
      audio.addEventListener('timeupdate',function(){if(Number.isFinite(audio.duration)&&audio.duration>0)progress.value=audio.currentTime/audio.duration*100;var seconds=Math.floor(audio.currentTime);elapsed.textContent=Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0');});
      audio.addEventListener('error',function(){play.disabled=true;progress.disabled=true;elapsed.textContent='음원을 불러올 수 없어요';});
      progress.addEventListener('input',function(){if(!state.editing&&Number.isFinite(audio.duration))audio.currentTime=Number(progress.value)/100*audio.duration;});
      volume.addEventListener('input',function(){if(!state.editing)audio.volume=Number(volume.value);});
      controls.append(play,progress);meta.append(elapsed,volume);content.append(title,controls,meta,audio);
    }else if(widget.type==='category'){
      content.className='pair-widget-content pair-widget-category style-'+(data.style||'buttons')+' layout-'+(data.layout||'vertical');content.style.setProperty('--widget-accent',data.accent||'#829782');var heading=document.createElement('h3');heading.textContent=data.title||'DIRECTORY';content.appendChild(heading);var list=document.createElement('div');list.className='pair-category-list';(data.items||[]).forEach(function(item,index){var button=document.createElement('button');button.type='button';var number=document.createElement('span');number.className='pair-category-number';number.textContent=String(index+1).padStart(2,'0');var text=document.createElement('span');text.className='pair-category-label';text.textContent=item.label||'메뉴';button.append(number,text);button.disabled=!item.url;button.addEventListener('click',function(e){e.stopPropagation();navigate(item.url,!!data.new_tab);});list.appendChild(button);});content.appendChild(list);
    }
  }
  function addEmpty(content,label){var empty=document.createElement('div');empty.className='pair-empty';empty.textContent=label;content.appendChild(empty);}
  function render(updatePanel){
    if(updatePanel===undefined)updatePanel=true;applyBackground();applyFrameTheme();canvas.innerHTML='';
    state.widgets.forEach(function(widget){var el=document.createElement('div');el.className='pair-widget'+(state.selectedId===widget.id&&state.editing?' is-selected':'')+(widget.locked&&state.editing?' is-locked':'');el.dataset.id=widget.id;el.dataset.type=widget.type;positionElement(el,widget);var content=document.createElement('div');renderContent(widget,content);el.appendChild(content);if(state.editing&&!widget.locked){var handle=document.createElement('span');handle.className='pair-resize-handle';handle.setAttribute('aria-hidden','true');el.appendChild(handle);}if(state.editing&&widget.locked){var badge=document.createElement('span');badge.className='pair-lock-badge';badge.textContent='잠금';badge.setAttribute('aria-label','잠긴 위젯');el.appendChild(badge);}canvas.appendChild(el);});
    refreshGeometry();
    if(updatePanel)renderProperties();
  }
  function positionElement(el,widget){
    var rect=canvas.getBoundingClientRect();if(!rect.width||!rect.height)return;
    var geometry=widgetGeometry(widget,rect);
    el.style.left=geometry.x+'%';el.style.top=geometry.y+'%';el.style.width=geometry.w+'%';el.style.height=geometry.h+'%';
    el.style.zIndex=clamp(Number(widget.z)||1,1,999);el.style.transform='rotate('+widget.rotation+'deg)';
  }
  function refreshGeometry(){
    var rect=canvas.getBoundingClientRect();
    canvas.style.setProperty('--pair-text-scale',Math.min(1,rect.width/960));
    canvas.querySelectorAll('.pair-widget').forEach(function(el){var widget=byId(el.dataset.id);if(widget)positionElement(el,widget);});
  }
  function field(label,type,value,key,options){var wrap=document.createElement('label');wrap.className='pair-editor-field';var caption=document.createElement('span');caption.textContent=label;wrap.appendChild(caption);var input;if(type==='textarea')input=document.createElement('textarea');else if(type==='select'){input=document.createElement('select');(options||[]).forEach(function(option){var node=document.createElement('option');node.value=option.value;node.textContent=option.label;input.appendChild(node);});}else{input=document.createElement('input');input.type=type;}input.value=value==null?'':value;input.dataset.key=key;wrap.appendChild(input);return wrap;}
  function renderProperties(){
    if(!config.admin)return;var panel=document.getElementById('pair-editor-panel');if(!panel)return;panel.innerHTML='';
    if(!state.editing){panel.classList.remove('is-open');return;}var widget=byId(state.selectedId);if(!widget){panel.classList.remove('is-open');return;}panel.classList.add('is-open');
    var title=document.createElement('h2');title.textContent='위젯 설정 · '+widget.type;panel.appendChild(title);var data=widget.data||{};
    if(widget.type==='image'){panel.appendChild(field('프레임 비율','select',data.ratio||'1:1','ratio',[{value:'1:1',label:'정사각형 · 1:1'},{value:'2:3',label:'세로 · 2:3'},{value:'3:4',label:'세로 · 3:4'},{value:'3:2',label:'가로 · 3:2'},{value:'4:3',label:'가로 · 4:3'},{value:'9:16',label:'세로 · 9:16'},{value:'16:9',label:'가로 · 16:9'}]));panel.appendChild(field('모서리','select',data.shape||'rounded','shape',[{value:'square',label:'각진 모서리'},{value:'rounded',label:'둥근 모서리'},{value:'circle',label:'원형'}]));if((data.shape||'rounded')==='rounded')panel.appendChild(field('둥근 정도','range',data.radius==null?18:data.radius,'radius'));panel.appendChild(field('사진 확대','range',data.zoom||1,'zoom'));panel.appendChild(field('사진 초점 · 가로','range',data.focus_x==null?50:data.focus_x,'focus_x'));panel.appendChild(field('사진 초점 · 세로','range',data.focus_y==null?50:data.focus_y,'focus_y'));panel.appendChild(field('대체 텍스트','text',data.alt||'','alt'));panel.appendChild(field('연결 주소','text',data.link||'','link'));var radiusInput=panel.querySelector('[data-key="radius"]');if(radiusInput){radiusInput.min=0;radiusInput.max=80;radiusInput.step=1;}var zoomInput=panel.querySelector('[data-key="zoom"]');if(zoomInput){zoomInput.min=1;zoomInput.max=3;zoomInput.step=.05;}['focus_x','focus_y'].forEach(function(key){var focusInput=panel.querySelector('[data-key="'+key+'"]');if(focusInput){focusInput.min=0;focusInput.max=100;focusInput.step=1;}});}
    else if(widget.type==='sticker'){panel.appendChild(field('투명도','range',data.opacity==null?1:data.opacity,'opacity'));panel.appendChild(field('좌우 방향','select',data.flip_x?'1':'0','flip_x',[{value:'0',label:'원본 방향'},{value:'1',label:'좌우 반전'}]));panel.appendChild(field('대체 텍스트','text',data.alt||'','alt'));panel.appendChild(field('연결 주소','text',data.link||'','link'));var opacityInput=panel.querySelector('[data-key="opacity"]');if(opacityInput){opacityInput.min=.1;opacityInput.max=1;opacityInput.step=.05;}}
    else if(widget.type==='text'){panel.appendChild(field('내용','textarea',data.text||'','text'));panel.appendChild(field('글꼴','select',data.font||'serif','font',[{value:'sans',label:'기본 고딕'},{value:'serif',label:'명조'},{value:'handwriting',label:'손글씨'}]));panel.appendChild(field('글자 크기','range',data.font_size==null?48:data.font_size,'font_size'));panel.appendChild(field('글자색','color',data.color||'#282326','color'));panel.appendChild(field('굵기','select',data.weight||'normal','weight',[{value:'normal',label:'보통'},{value:'bold',label:'굵게'}]));panel.appendChild(field('정렬','select',data.align||'left','align',[{value:'left',label:'왼쪽'},{value:'center',label:'가운데'},{value:'right',label:'오른쪽'}]));panel.appendChild(field('줄 간격','range',data.line_height==null?1.05:data.line_height,'line_height'));panel.appendChild(field('연결 주소','text',data.link||'','link'));var fontSizeInput=panel.querySelector('[data-key="font_size"]');if(fontSizeInput){fontSizeInput.min=12;fontSizeInput.max=160;fontSizeInput.step=1;}var lineHeightInput=panel.querySelector('[data-key="line_height"]');if(lineHeightInput){lineHeightInput.min=.8;lineHeightInput.max=2.5;lineHeightInput.step=.05;}}
    else if(widget.type==='dday'){panel.appendChild(field('제목','text',data.title||'','title'));panel.appendChild(field('기준일','date',data.date||'','date'));panel.appendChild(field('계산 방식','select',data.mode||'since','mode',[{value:'since',label:'기준일부터'},{value:'until',label:'기준일까지'}]));panel.appendChild(field('첫날 계산','select',data.include_today===false?'0':'1','include_today',[{value:'1',label:'첫날을 D+1로 계산'},{value:'0',label:'첫날을 D-DAY로 계산'}]));panel.appendChild(field('날짜 표시','select',data.show_date===false?'0':'1','show_date',[{value:'1',label:'표시'},{value:'0',label:'숨김'}]));panel.appendChild(field('스타일','select',data.style||'lcd','style',[{value:'lcd',label:'LCD'},{value:'label',label:'날짜 라벨'},{value:'plain',label:'심플'}]));panel.appendChild(field('포인트색','color',data.accent||'#829782','accent'));}
    else if(widget.type==='bgm'){panel.appendChild(field('곡명','text',data.title||'','title'));panel.appendChild(field('음원 주소','text',data.src||'','src'));panel.appendChild(field('반복 재생','select',data.loop?'1':'0','loop',[{value:'1',label:'반복'},{value:'0',label:'한 번 재생'}]));panel.appendChild(field('기본 볼륨','range',data.volume==null?.8:data.volume,'volume'));var volumeInput=panel.querySelector('[data-key="volume"]');if(volumeInput){volumeInput.min=0;volumeInput.max=1;volumeInput.step=.05;}}
    else if(widget.type==='category'){panel.appendChild(field('제목','text',data.title||'','title'));panel.appendChild(field('메뉴 항목 · 이름|주소','textarea',(data.items||[]).map(function(i){return i.label+'|'+(i.url||'');}).join('\n'),'items'));panel.appendChild(field('스타일','select',data.style||'buttons','style',[{value:'buttons',label:'노트 버튼'},{value:'directory',label:'인덱스 목록'},{value:'plain',label:'심플'}]));panel.appendChild(field('배치','select',data.layout||'vertical','layout',[{value:'vertical',label:'세로'},{value:'horizontal',label:'가로'}]));panel.appendChild(field('링크 열기','select',data.new_tab?'1':'0','new_tab',[{value:'0',label:'현재 화면'},{value:'1',label:'새 창'}]));panel.appendChild(field('포인트색','color',data.accent||'#829782','accent'));}
    panel.appendChild(field('회전','range',widget.rotation,'rotation'));var range=panel.querySelector('[data-key="rotation"]');if(range){range.min=-30;range.max=30;range.step=1;}
    var actions=document.createElement('div');actions.className='pair-editor-actions';
    if(widget.type==='image'||widget.type==='sticker'){var upload=document.createElement('button');upload.type='button';upload.textContent='이미지 업로드';upload.addEventListener('click',function(){activeUploadWidgetId=widget.id;document.getElementById('pair-asset-upload').click();});actions.appendChild(upload);}
    if(widget.type==='bgm'){var audioUpload=document.createElement('button');audioUpload.type='button';audioUpload.textContent='음원 업로드';audioUpload.addEventListener('click',function(){activeAudioWidgetId=widget.id;document.getElementById('pair-audio-upload').click();});actions.appendChild(audioUpload);var audioClear=document.createElement('button');audioClear.type='button';audioClear.textContent='음원 제거';audioClear.disabled=!data.src;audioClear.addEventListener('click',function(){widget.data.src='';render();markDirty();});actions.appendChild(audioClear);}
    var duplicate=document.createElement('button');duplicate.type='button';duplicate.textContent='복제';duplicate.addEventListener('click',function(){var copy=clone(widget);copy.id=newId(widget.type);copy.x=clamp(Number(copy.x)+3,0,100-copy.w);copy.y=clamp(Number(copy.y)+3,0,100-copy.h);copy.z=state.widgets.reduce(function(max,item){return Math.max(max,item.z||1);},0)+1;copy.locked=false;state.widgets.push(copy);state.selectedId=copy.id;render();markDirty();});actions.appendChild(duplicate);
    var backward=document.createElement('button');backward.type='button';backward.textContent='뒤로';backward.addEventListener('click',function(){widget.z=Math.max(1,(widget.z||1)-1);render();markDirty();});actions.appendChild(backward);
    var front=document.createElement('button');front.type='button';front.textContent='앞으로';front.addEventListener('click',function(){widget.z=Math.min(999,(widget.z||1)+1);render();markDirty();});actions.appendChild(front);
    var lock=document.createElement('button');lock.type='button';lock.textContent=widget.locked?'잠금 해제':'잠금';lock.addEventListener('click',function(){widget.locked=!widget.locked;render();markDirty();});actions.appendChild(lock);
    var remove=document.createElement('button');remove.type='button';remove.className='pair-danger';remove.textContent='삭제';remove.addEventListener('click',function(){state.widgets=state.widgets.filter(function(i){return i.id!==widget.id;});state.selectedId=null;render();markDirty();});actions.appendChild(remove);panel.appendChild(actions);
    panel.querySelectorAll('[data-key]').forEach(function(input){input.addEventListener('input',function(){var key=input.dataset.key;if(key==='rotation')widget.rotation=Number(input.value);else if(key==='items')widget.data.items=input.value.split(/\r?\n/).map(function(line){var at=line.indexOf('|');return{label:(at>=0?line.slice(0,at):line).trim(),url:(at>=0?line.slice(at+1):'').trim()};}).filter(function(i){return i.label;});else if(key==='zoom'||key==='focus_x'||key==='focus_y'||key==='radius'||key==='volume'||key==='opacity'||key==='font_size'||key==='line_height')widget.data[key]=Number(input.value);else if(key==='loop'||key==='flip_x'||key==='include_today'||key==='show_date'||key==='new_tab')widget.data[key]=input.value==='1';else{widget.data[key]=input.value;if(key==='shape'&&input.value==='circle')widget.data.ratio='1:1';if(key==='ratio'&&widget.data.shape==='circle'&&input.value!=='1:1')widget.data.shape='rounded';}if(key==='shape'||key==='ratio')fitFixedRatioWidget(widget);render(key==='shape'||key==='ratio');markDirty();});});
  }
  function addWidget(type){var defaults={image:{src:'',shape:'rounded',radius:18,ratio:'1:1',zoom:1,focus_x:50,focus_y:50,alt:'',link:''},sticker:{src:'',opacity:1,flip_x:false,aspect:0,alt:'',link:''},text:{text:'새 텍스트',font:'serif',font_size:48,color:'#282326',weight:'normal',align:'left',line_height:1.05,link:''},dday:{title:'SINCE',date:new Date().toISOString().slice(0,10),mode:'since',include_today:true,show_date:true,style:'lcd',accent:'#829782'},bgm:{title:'BGM',src:'',loop:true,volume:.8},category:{title:'DIRECTORY',style:'buttons',layout:'vertical',new_tab:false,accent:'#829782',items:[{label:'NEW LINK',url:''}]}};var z=state.widgets.reduce(function(max,w){return Math.max(max,w.z||1);},0);var widget={id:newId(type),type:type,x:35,y:30,w:type==='sticker'?14:24,h:type==='text'?14:24,rotation:0,z:z+1,locked:false,data:defaults[type]};state.widgets.push(widget);state.selectedId=widget.id;render();markDirty();}
  function showStatus(message){var status=document.getElementById('pair-editor-status');if(!status)return;status.textContent=message;status.style.display='block';clearTimeout(statusTimer);statusTimer=setTimeout(function(){status.style.display='none';},2800);}
  async function uploadImage(file,kind){var form=new FormData();form.append('action','upload');form.append('kind',kind);form.append('token',config.token||'');form.append('image',file);var response=await fetch(config.apiUrl,{method:'POST',body:form,credentials:'same-origin'});var result=await response.json();if(!response.ok||result.error)throw new Error(result.error||'업로드에 실패했습니다.');return result;}
  async function uploadAudio(file){var form=new FormData();form.append('action','upload_audio');form.append('token',config.token||'');form.append('audio',file);var response=await fetch(config.apiUrl,{method:'POST',body:form,credentials:'same-origin'});var result=await response.json();if(!response.ok||result.error)throw new Error(result.error||'음원 업로드에 실패했습니다.');return result.url;}
  async function save(){if(isSaving||!isDirty())return;state.widgets.forEach(fitFixedRatioWidget);isSaving=true;updateDirtyUi();try{var form=new FormData();form.append('action','save');form.append('token',config.token||'');form.append('layout',JSON.stringify(state.widgets));form.append('background_color',state.backgroundColor);form.append('background_image',state.backgroundImage);form.append('frame_theme',state.frameTheme);var response=await fetch(config.apiUrl,{method:'POST',body:form,credentials:'same-origin'});var result=await response.json();if(!response.ok||result.error)throw new Error(result.error||'저장에 실패했습니다.');state.widgets=result.layout;savedState=serializeState();render();showStatus('저장했습니다.');}finally{isSaving=false;updateDirtyUi();}}
  function openBackground(){var panel=document.getElementById('pair-editor-panel');state.selectedId=null;canvas.querySelectorAll('.is-selected').forEach(function(el){el.classList.remove('is-selected');});panel.innerHTML='';panel.classList.add('is-open');var title=document.createElement('h2');title.textContent='배경과 기본 테마';panel.appendChild(title);var theme=field('기본 테마','select',state.frameTheme,'frameTheme',[{value:'web',label:'웹창 · 상단바 일체형'},{value:'diary',label:'다이어리 · 링과 아이콘 탭'},{value:'mac',label:'웹창 · 맥 상단바 분리형'}]);panel.appendChild(theme);theme.querySelector('select').addEventListener('input',function(e){state.frameTheme=e.target.value;applyFrameTheme();state.widgets.forEach(fitFixedRatioWidget);render(false);markDirty();});var color=field('배경색','color',state.backgroundColor,'backgroundColor');panel.appendChild(color);color.querySelector('input').addEventListener('input',function(e){state.backgroundColor=e.target.value.toUpperCase();applyBackground();markDirty();});var note=document.createElement('p');note.className='pair-editor-note';note.textContent='종이 안쪽이 자유 꾸밈 영역입니다. 링과 배경 장식은 위젯 아래에 놓이며, 회전한 위젯도 본문 안에 유지됩니다. 배경 이미지는 비율을 유지한 채 화면을 채우며 넘치는 부분은 자동으로 잘립니다.';panel.appendChild(note);var actions=document.createElement('div');actions.className='pair-editor-actions';var upload=document.createElement('button');upload.type='button';upload.textContent='배경 이미지 업로드';upload.addEventListener('click',function(){document.getElementById('pair-background-upload').click();});var clear=document.createElement('button');clear.type='button';clear.textContent='배경 이미지 제거';clear.addEventListener('click',function(){state.backgroundImage='';applyBackground();markDirty();});actions.append(upload,clear);panel.appendChild(actions);}
  canvas.addEventListener('pointerdown',function(event){if(!state.editing)return;var el=event.target.closest('.pair-widget');if(!el){state.selectedId=null;render();return;}event.preventDefault();state.selectedId=el.dataset.id;canvas.querySelectorAll('.pair-widget').forEach(function(node){node.classList.toggle('is-selected',node===el);});renderProperties();var widget=byId(state.selectedId);if(!widget||widget.locked)return;var rect=canvas.getBoundingClientRect();var geometry=widgetGeometry(widget,rect);interaction={id:widget.id,mode:event.target.classList.contains('pair-resize-handle')?'resize':'move',startX:event.clientX,startY:event.clientY,x:geometry.x,y:geometry.y,w:geometry.w,h:geometry.h,rect:rect,changed:false};el.setPointerCapture(event.pointerId);});
  window.addEventListener('pointermove',function(event){if(!interaction)return;var widget=byId(interaction.id);if(!widget)return;event.preventDefault();widget.x=interaction.x;widget.y=interaction.y;widget.w=interaction.w;widget.h=interaction.h;var dxPixels=event.clientX-interaction.startX,dyPixels=event.clientY-interaction.startY;var dx=dxPixels/interaction.rect.width*100,dy=dyPixels/interaction.rect.height*100;if(interaction.mode==='move'){widget.x=clamp(interaction.x+dx,0,100-widget.w);widget.y=clamp(interaction.y+dy,0,100-interaction.h);}else if(fixedRatio(widget)){var ratio=fixedRatio(widget);var startWidthPixels=interaction.w/100*interaction.rect.width;var startHeightPixels=interaction.h/100*interaction.rect.height;var targetWidthPixels=Math.abs(dxPixels)>=Math.abs(dyPixels)?startWidthPixels+dxPixels:(startHeightPixels+dyPixels)*ratio;var maxWidthPixels=Math.min((100-widget.x)/100*interaction.rect.width,(100-widget.y)/100*interaction.rect.height*ratio);widget.w=clamp(targetWidthPixels/interaction.rect.width*100,4,maxWidthPixels/interaction.rect.width*100);widget.h=visualHeightPercent(widget,interaction.rect);}else{widget.w=clamp(interaction.w+dx,4,100-widget.x);widget.h=clamp(interaction.h+dy,4,100-widget.y);}fitFixedRatioWidget(widget);interaction.changed=true;var el=canvas.querySelector('[data-id="'+widget.id+'"]');if(el)positionElement(el,widget);});
  function endInteraction(){if(interaction&&interaction.changed)markDirty();interaction=null;}
  window.addEventListener('pointerup',endInteraction);window.addEventListener('pointercancel',endInteraction);
  if(config.admin){
    document.getElementById('pair-editor-toggle').addEventListener('click',function(){state.editing=!state.editing;shell.classList.toggle('is-editing',state.editing);if(!state.editing)state.selectedId=null;render();updateDirtyUi();});
    document.querySelectorAll('[data-add]').forEach(function(button){button.addEventListener('click',function(){addWidget(button.dataset.add);});});
    document.getElementById('pair-background-open').addEventListener('click',openBackground);
    document.getElementById('pair-reset').addEventListener('click',restoreSaved);
    document.getElementById('pair-save').addEventListener('click',function(){save().catch(function(error){showStatus(error.message);});});
    document.getElementById('pair-asset-upload').addEventListener('change',function(e){var file=e.target.files[0],widget=byId(activeUploadWidgetId);if(!file||!widget)return;uploadImage(file,'asset').then(function(result){widget.data.src=result.url;if(widget.type==='sticker'&&Number(result.width)>0&&Number(result.height)>0){widget.data.aspect=Number(result.width)/Number(result.height);fitFixedRatioWidget(widget);}render();markDirty();showStatus('이미지를 추가했습니다.');}).catch(function(error){showStatus(error.message);});e.target.value='';});
    document.getElementById('pair-background-upload').addEventListener('change',function(e){var file=e.target.files[0];if(!file)return;uploadImage(file,'background').then(function(result){state.backgroundImage=result.url;applyBackground();markDirty();showStatus('배경 이미지를 적용했습니다.');}).catch(function(error){showStatus(error.message);});e.target.value='';});
    document.getElementById('pair-audio-upload').addEventListener('change',function(e){var file=e.target.files[0],widget=byId(activeAudioWidgetId);if(!file||!widget)return;uploadAudio(file).then(function(url){widget.data.src=url;render();markDirty();showStatus('음원을 추가했습니다.');}).catch(function(error){showStatus(error.message);});e.target.value='';});
    window.addEventListener('beforeunload',function(event){if(!isDirty())return;event.preventDefault();event.returnValue='';});
    updateDirtyUi();
  }
  render();
  if(window.ResizeObserver){new ResizeObserver(refreshGeometry).observe(canvas);}else{window.addEventListener('resize',refreshGeometry);}
})();
