CREATE TABLE `__TABLE_NAME__` (
  `wr_id` int(11) NOT NULL AUTO_INCREMENT,
  `wr_num` int(11) NOT NULL DEFAULT '0',
  `wr_reply` varchar(10) NOT NULL,
  `wr_parent` int(11) NOT NULL DEFAULT '0',
  `wr_is_comment` tinyint(4) NOT NULL DEFAULT '0',
  `wr_comment` int(11) NOT NULL DEFAULT '0',
  `wr_comment_reply` varchar(5) NOT NULL,
  `ca_name` varchar(255) NOT NULL,
  `wr_option` varchar(255) NOT NULL DEFAULT '',
  `wr_secret` varchar(255) NOT NULL DEFAULT '',
  `wr_subject` varchar(255) NOT NULL,
  `wr_title` varchar(255) NOT NULL DEFAULT '',
  `wr_english_title` varchar(255) NOT NULL DEFAULT '',
  `wr_catchphrase` varchar(500) NOT NULL DEFAULT '',
  `wr_playtime` varchar(50) NOT NULL DEFAULT '',
  `wr_kpc` varchar(255) NOT NULL DEFAULT '',
  `wr_pc` varchar(255) NOT NULL DEFAULT '',
  `wr_subject_font` varchar(255) NOT NULL DEFAULT '',
  `wr_subject_color` varchar(7) NOT NULL DEFAULT '',
  `wr_english_title_font` varchar(255) NOT NULL DEFAULT '',
  `wr_english_title_color` varchar(7) NOT NULL DEFAULT '',
  `wr_subtitle_font` varchar(255) NOT NULL DEFAULT '',
  `wr_subtitle_color` varchar(7) NOT NULL DEFAULT '',
  `wr_catchphrase_font` varchar(255) NOT NULL DEFAULT '',
  `wr_catchphrase_color` varchar(7) NOT NULL DEFAULT '',
  `wr_img` varchar(255) NOT NULL DEFAULT '',
  `wr_type` varchar(50) NOT NULL DEFAULT '',
  `wr_content` LONGTEXT NOT NULL,
  `wr_link1` text NOT NULL,
  `wr_link2` text NOT NULL,
  `wr_adult` tinyint(4) NOT NULL DEFAULT '0',
  `wr_plip` tinyint(4) NOT NULL DEFAULT '0',
  `wr_wide` tinyint(4) NOT NULL DEFAULT '0',
  `wr_url` text NOT NULL,
  `wr_hit` int(11) NOT NULL DEFAULT '0',
  `mb_id` varchar(20) NOT NULL,
  `ch_id` int(11) NOT NULL DEFAULT '0',
  `ch_name` varchar(100) NOT NULL DEFAULT '',
  `ch_img` varchar(255) NOT NULL DEFAULT '',
  `ch_fa_id` int(11) NOT NULL DEFAULT '0',
  `ch_fa_name` varchar(100) NOT NULL DEFAULT '',
  `ch_fa_color` varchar(7) NOT NULL DEFAULT '',
  `ch_rk_id` int(11) NOT NULL DEFAULT '0',
  `ch_rk_name` varchar(100) NOT NULL DEFAULT '',
  `ch_title_id` int(11) NOT NULL DEFAULT '0',
  `ch_title_name` varchar(100) NOT NULL DEFAULT '',
  `wr_password` varchar(255) NOT NULL,
  `wr_name` varchar(255) NOT NULL,
  `wr_email` varchar(255) NOT NULL,
  `wr_homepage` varchar(255) NOT NULL,
  `wr_datetime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `wr_file` tinyint(4) NOT NULL DEFAULT '0',
  `wr_last` varchar(19) NOT NULL,
  `wr_ip` varchar(255) NOT NULL,
  `wr_1` varchar(255) NOT NULL,
  `wr_2` varchar(255) NOT NULL,
  `wr_3` varchar(255) NOT NULL,
  `wr_4` varchar(255) NOT NULL,
  `wr_5` text NOT NULL,
  `wr_6` varchar(255) NOT NULL,
  `wr_7` varchar(255) NOT NULL,
  `wr_8` varchar(255) NOT NULL,
  `wr_9` varchar(255) NOT NULL,
  `wr_10` varchar(255) NOT NULL,
  `wr_order` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`wr_id`),
  KEY `wr_num_reply_parent` (`wr_num`,`wr_reply`,`wr_parent`),
  KEY `wr_is_comment` (`wr_is_comment`,`wr_id`),
  KEY `ch_id` (`ch_id`),
  KEY `wr_order` (`wr_order`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
