-- ra0_write_trpg_log의 LONGTEXT 단일 본문 저장 전환
-- wr_1_txt ~ wr_40_txt는 기존 분산 저장용 컬럼이며 현재 게시글이 없을 때 삭제합니다.
SET SESSION sql_mode = '';

ALTER TABLE `ra0_write_trpg_log`
    MODIFY COLUMN `wr_content` LONGTEXT NOT NULL,
    MODIFY COLUMN `wr_5` TEXT NOT NULL,
    DROP COLUMN `wr_1_txt`,
    DROP COLUMN `wr_2_txt`,
    DROP COLUMN `wr_3_txt`,
    DROP COLUMN `wr_4_txt`,
    DROP COLUMN `wr_5_txt`,
    DROP COLUMN `wr_6_txt`,
    DROP COLUMN `wr_7_txt`,
    DROP COLUMN `wr_8_txt`,
    DROP COLUMN `wr_9_txt`,
    DROP COLUMN `wr_10_txt`,
    DROP COLUMN `wr_11_txt`,
    DROP COLUMN `wr_12_txt`,
    DROP COLUMN `wr_13_txt`,
    DROP COLUMN `wr_14_txt`,
    DROP COLUMN `wr_15_txt`,
    DROP COLUMN `wr_16_txt`,
    DROP COLUMN `wr_17_txt`,
    DROP COLUMN `wr_18_txt`,
    DROP COLUMN `wr_19_txt`,
    DROP COLUMN `wr_20_txt`,
    DROP COLUMN `wr_21_txt`,
    DROP COLUMN `wr_22_txt`,
    DROP COLUMN `wr_23_txt`,
    DROP COLUMN `wr_24_txt`,
    DROP COLUMN `wr_25_txt`,
    DROP COLUMN `wr_26_txt`,
    DROP COLUMN `wr_27_txt`,
    DROP COLUMN `wr_28_txt`,
    DROP COLUMN `wr_29_txt`,
    DROP COLUMN `wr_30_txt`,
    DROP COLUMN `wr_31_txt`,
    DROP COLUMN `wr_32_txt`,
    DROP COLUMN `wr_33_txt`,
    DROP COLUMN `wr_34_txt`,
    DROP COLUMN `wr_35_txt`,
    DROP COLUMN `wr_36_txt`,
    DROP COLUMN `wr_37_txt`,
    DROP COLUMN `wr_38_txt`,
    DROP COLUMN `wr_39_txt`,
    DROP COLUMN `wr_40_txt`;
